### ISSUE TITLE
可以添加requirements.txt文件 给出对应依赖和版面吗

### ISSUE THREAD

**Issue by Youth99** [81NewArk/StupidOCR#11]
可以添加requirements.txt文件 给出对应依赖和版面吗

**Comment by 81NewArk** [comment]
已经提供

**Comment by Youth99** [comment]
self.Button_Stop.clicked.connect(self.stop_button_clicked)
AttributeError: 'Ui_MainWindow' object has no attribute 'stop_button_clicked'
