### ISSUE TITLE
状态码 500

### ISSUE THREAD

**Issue by dslll** [81NewArk/StupidOCR#7]
同样的格式 用普通验证码识别能正常返回  算术验证码就返回500 这是什么原因啊啊啊啊

**Comment by 81NewArk** [comment]
报错500 可以详细查看算数接口的代码

**Comment by dslll** [comment]
应该是识别不准确造成的原因 验证码18+5  有时会识别为18+5-  会导致代码错误

**Comment by yang7758258** [comment]
状态码500，同上，用算数码就报500
![image](https://github.com/81NewArk/StupidOCR/assets/43715693/42d8e43b-254a-44b6-aea4-390a8e8396b5)
